Script started on 2020-05-04 21:02:51-04:00 [TERM="xterm-kitty" TTY="/dev/pts/1" COLUMNS="78" LINES="35"]
]0;david@davidreidsma:~/Programming/Calvin/cs214/extra_cred_lab[david@davidreidsma extra_cred_lab]$ clojure
Clojure 1.10.1
user=> ((fn [x y z] (+ x y z)) 5 5 5)
15
user=> (fn    (fn [x  ] nil? x)^[[D^[[D^[[D^[[D^[[D                                    
user=> ((fn [x] (nil? x)) nil)
true
user=> ((fn [x] (nil? x)) 5)
false
user=> ((fn [] 17.2))
17.2
user=> 
]0;david@davidreidsma:~/Programming/Calvin/cs214/extra_cred_lab[david@davidreidsma extra_cred_lab]$ exit

Script done on 2020-05-04 21:09:12-04:00 [COMMAND_EXIT_CODE="0"]
