Script started on 2020-05-04 21:47:03-04:00 [TERM="xterm-kitty" TTY="/dev/pts/1" COLUMNS="78" LINES="35"]
]0;david@davidreidsma:~/Programming/Calvin/cs214/extra_cred_lab[david@davidreidsma extra_cred_lab]$ clojure
Clojure 1.10.1
user=> (def squareSquare (fn [x] (Math/pow (Math/pow x 2) 2)))
#'user/squareSquare
user=> (squareSquare 2)
16.0
user=> (squareSquare -2)
16.0
user=> (squareSquare 3)
81.0
user=> (squareSquare -3)
81.0
user=> 
]0;david@davidreidsma:~/Programming/Calvin/cs214/extra_cred_lab[david@davidreidsma extra_cred_lab]$ exit

Script done on 2020-05-04 21:48:52-04:00 [COMMAND_EXIT_CODE="0"]
