Script started on 2020-03-12 15:42:34-0400
[1m[7m%[27m[1m[0m                                                                                                                                            ]2;david@david-ThinkPad-P52s: ~/Programming/Calvin/cs214/lab06]1;..n/cs214/lab06[0m[27m[24m[J[01;32m➜  [36mlab06[00m [01;34mgit:([31mmaster[34m) [33m✗[00m [K[?1h=[?2004h[4mc[24m[24m[32mc[32md[39m [4mj[24m[4mj[4ma[24m[4ma[4mv[24m[4mv[4ma[24m[?1l>[?2004l
]2;cd java]1;cd[1m[7m%[27m[1m[0m                                                                                                                                            ]2;david@david-ThinkPad-P52s: ~/Programming/Calvin/cs214/lab06/java]1;..14/lab06/java[0m[27m[24m[J[01;32m➜  [36mjava[00m [01;34mgit:([31mmaster[34m) [33m✗[00m [K[?1h=[?2004h[1m[31mc[0m[39m[1m[31mc[1m[31ma[0m[39m[0m[32mc[0m[32ma[32mt[39m [4mAverage.[24m[4m.[4mj[24m[4mj[4ma[24m[4ma[4mv[24m[4mv[4ma[24m[?1l>[?2004l
]2;cat Average.java]1;cat/* Average.java is a driver for method avg().
 *
 * Started by: Prof. Adams, for CS 214 at Calvin College
 *
 * Student Name: 	David Reidsma
 * Date:			03/12/2020
 *
 * Precondition: array, is an array of double values.
 * Output: the average of the numbers in array.
 ***************************************************************/

import java.io.*;

public class Average {
	public static void main(String[] args) {
		double[] array0 = new double[0];
		double[] array1 = { 9.0, 8.0, 7.0, 6.0 };

		// output the average of the values in the arrays
		System.out.println("The first average is " + avg(array0));
		System.out.println("The second average is " + avg(array1));
	}

	/*
	 * sum() is a method that computes the sum of all the values in an array of doubles.
	 * Receive: array, an array of doubles.
	 * Return: the sum of the values in array.
	 ************************************************************/
	static double sum(double[] array) {
		double total = 0.0;
		for (int i = 0; i < array.length; i++) {
			total += array[i];
		}
		return total;
	}

	/*
	 * avg() is a method that computes the average of the values in an array.
	 * Receive: array, an array of doubles.
	 * Return: the average of the values in array.
	 **************************************************************/
	static double avg(double array[]) {
		if (array == null || array.length <= 0)
			return 0.0;
		
		return sum(array) / array.length;
	}
}
[1m[7m%[27m[1m[0m                                                                                                                                            ]2;david@david-ThinkPad-P52s: ~/Programming/Calvin/cs214/lab06/java]1;..14/lab06/java[0m[27m[24m[J[01;32m➜  [36mjava[00m [01;34mgit:([31mmaster[34m) [33m✗[00m [K[?1h=[?2004h[1m[31mj[0m[39m[1m[31mj[1m[31ma[0m[39m[1m[31mj[1m[31ma[1m[31mv[0m[39m[0m[32mj[0m[32ma[0m[32mv[32ma[39m[32ma[32mc[39m -deprecation [4mA[24m[4mA[4mv[24m[4mv[4me[24m[4me[4mr[24m[4mr[4ma[24m[4ma[4mg[24m[4mg[4me[24m[4me[4m.[24m[4m.[4mj[24m[4mj[4ma[24m[4ma[4mv[24m[4mv[4ma[24m[?1l>[?2004l
]2;javac -deprecation Average.java]1;javac[1m[7m%[27m[1m[0m                                                                                                                                            ]2;david@david-ThinkPad-P52s: ~/Programming/Calvin/cs214/lab06/java]1;..14/lab06/java[0m[27m[24m[J[01;32m➜  [36mjava[00m [01;34mgit:([31mmaster[34m) [33m✗[00m [K[?1h=[?2004h[1m[31mj[0m[39m[1m[31mj[1m[31ma[0m[39m[1m[31mj[1m[31ma[1m[31mv[0m[39m[0m[32mj[0m[32ma[0m[32mv[32ma[39m [4mA[24m[4mA[4mv[24m[4mv[4me[24m[4me[4mr[24m[4mr[4ma[24m[4ma[4mg[24m[4mg[4me[24m[?1l>[?2004l[24mA[24mv[24me[24mr[24ma[24mg[24me
]2;java Average]1;javaThe first average is 0.0
The second average is 7.5
[1m[7m%[27m[1m[0m                                                                                                                                            ]2;david@david-ThinkPad-P52s: ~/Programming/Calvin/cs214/lab06/java]1;..14/lab06/java[0m[27m[24m[J[01;32m➜  [36mjava[00m [01;34mgit:([31mmaster[34m) [33m✗[00m [K[?1h=[?2004h[?2004l

Script done on 2020-03-12 15:43:53-0400
